spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop #자동으로 스키마 작성 create / create-drop / update / validate / none , 개발단계에서만 사용, 실무사용 x
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # 자동 스네이크 변환 방지
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect # 좀더 postgresql 로 SQL문으로 변환되게함.
  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: board-master
    password: tkadlf31
  security:
    user.name: board-admin
    user.password: board-admin-password
  logging:
    level:
    # TRACE < DEBUG < INFO < WARN < ERROR 
     root: INFO
    
#    level:
#      org.hibernate.type: TRACE
#      org.hibernate.orm.jdbc.bind: TRACE
#      org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
#      org.springframework.orm.jpa: DEBUG
#      org.springframework.transaction: DEBUG